title: "SSH Autonomous Driving AI Challenge"
description: "自動運転AIチャレンジの活動記録"
theme: minima  # シンプルで見やすい公式テーマ
url: "https://SSH-autonomous-driving-aichallenge.github.io"
baseurl: ""    # ← ユーザーサイトなので空

markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# ナビゲーションメニューを作る
header_pages:
  - about.md
  - team.md
  - results/2025.md
